### ISSUE TITLE
IsisLabelIsisSpice can override spiceinit in ISIS

### ISSUE THREAD

**Issue by acpaquette** [DOI-USGS/ale#504]
If the only ISISLabel driver that exists for an instrument is the ISISLabelISISSPICE driver, the default spiceinit routines in ISIS will NOT put fresh spice data on the cube and simply regenerate the same spice data already available.

To test:
- Install ALE drivers into an env using the usual development install commend `python setup.py develop`
- Remove the ISISLabelNaifSpice driver from a mission/instrument that also has a ISISLabelISISSpice driver
- Run spiceinit and see that the source is still from ALE

**Comment by jessemapel** [comment]
I think we need to add some type of include/exclude option for loads so that ISIS only uses the NaifSpice drivers. I think something based on specific mix-ins would be helpful.
