### ISSUE TITLE
KaguyaTC DTM failures

### ISSUE THREAD

**Issue by kbauck-usgs** [DOI-USGS/ale#540]
Out of a test of 20 stereo pairs, 2 stereo pairs failed, both in the upper lattitude:

Data located at: /calscratch/global/kagtc_dtms/khb_uppertest/failed/*/
**Stereo Pair 1:** TC2W2B0_01_06988N522E1035.img & TC1W2B0_01_06988N514E1035.img
**Stereo Pair 2:** TC1W2B0_01_06988N529E1035.img  & TC2W2B0_01_06988N536E1035.img

Example of what these image stereo pairs look like:
<img width="450" alt="Dark_dtm" src="https://github.com/DOI-USGS/ale/assets/108542142/ccc2e509-f207-43be-8431-72cbf92f0017">
<img width="447" alt="Light_dtm" src="https://github.com/DOI-USGS/ale/assets/108542142/7431c9e2-c968-459a-9d71-a215d0b12518">

**Comment by acpaquette** [comment]
@kbauck-usgs Could I also get a link to the pipeline that is being run? If it's in a code.chs repo I may also need to be given access to said repo

**Comment by kbauck-usgs** [comment]
@acpaquette Yeah! It looks like you already have access, but let me know if you have any trouble. Thank you for your help! [This is the script](https://code.chs.usgs.gov/asc/automated-dtm-generation/-/blob/master/bin/make_dtm_array.sh) that runs the pipeline.

The 4 files it runs through are:
1. kagtc_edr2lev1.sh
2. kagtc_lev12low.sh
3. kagtc_map2full.sh
4. kagtc_full2ground.sh

I have been starting to wrangle with QGIS to see if I can get everything projected to the right CRS so I can look into the error I know Jay was seeing earlier with the DTMs being misaligned. The version of ALE you worked on (0.9.0) has been implemented and we defiantly saw better quality results. So if anything, if I cant get the projections right it might just be something with this pipeline.

**Comment by acpaquette** [comment]
@jlaura @kbauck-usgs Can this be closed per the post in teams, or should this remain open for now?

**Comment by jlaura** [comment]
Browsing issues - this can be closed. The driver is working as expected.
