### ISSUE TITLE
Sync up ale library version

### ISSUE THREAD

**Issue by oleg-alexandrov** [DOI-USGS/ale#554]
Ale 0.9.1 uses version string 0.9.0 in the CMake file at https://github.com/DOI-USGS/ale/blob/0.9.1/CMakeLists.txt. It also creates libale.0.9.0.dylib. I am not sure this is important, but it make sense, perhaps, to update the version in that file.

**Comment by acpaquette** [comment]
Got missed in the release :(

**Comment by oleg-alexandrov** [comment]
Looks like this is moot given the release of 0.10.0. Both for the newest version, and for the latest in main, the version is correct.
