### ISSUE TITLE
Verify Spice-based ALE drivers against ISIS

### ISSUE THREAD

**Issue by Kelvinrr** [DOI-USGS/ale#562]
We now have a lot of drivers available now, we need to figure out some way to rigorously validate these drivers against ISIS spice code. This will be necessary to be able to depreciate ISIS's existing code.

**Comment by antonhibl** [comment]
working on this at https://github.com/antonhibl/ale/blob/spice-verification/ale/driver_verification.py, will make a PR when the script is more fleshed out but it definitely needs more work. I think it shows some of the ideas we want to accomplish though.

**Comment by antonhibl** [comment]
This should be finished as of #584 being merged, which added a driver verification script to verify between ISIS and ALE spice outputs.
