### ISSUE TITLE
Fix disabled drivers

### ISSUE THREAD

**Issue by acpaquette** [DOI-USGS/ale#581]
Currently ALE has a few disabled drivers:

- [x] ody
    - [ ] tests
- [x] hayabusa2
    - [x] tests
- [x] juno
    - [x] tests
- [x] msi
    - [x] tests

These should be fixed for a 1.0 release.

TGO will remain disabled - it has a special case that we will have to deal with in the future.

**Comment by jrcain-usgs** [comment]
Any context on why these were disabled?  Was there some specific problem that affected them all, were they incomplete, did they just need tests?

I see that in ale > drivers > __init__.py there's a list of disabled drivers at the top.  In the tests, the test_x_load() for each is marked with @pytest.mark.xfail so their failures will be skipped.

**Comment by acpaquette** [comment]
Actually, looking over things. It seems like TGO is the only driver left. If we could double check that the drivers have tests that would be the last thing for this issue

**Comment by jrcain-usgs** [comment]
@acpaquette 
It sounds like there's something I don't know about TGO.
Could you open a different issue for TGO with a bit more on what that special case is?
