### ISSUE TITLE
Mystery with MSL camera generation

### ISSUE THREAD

**Issue by oleg-alexandrov** [DOI-USGS/ale#588]
I found a very strange issue that defies any explanation, and no attempt at debugging offers any clues. With no changes whatsoever to the ale code, kernels, spice, etc, CSM cameras produced by ALE are now wrong. 

One notable change in the produced .json camera files is that instead of:

"instrument_pointing": {
    "time_dependent_frames": [
      -76000,
      -76910,
      -76900,
      10014,
      1
    ],

there is now:

"instrument_pointing": {
    "time_dependent_frames": [
      -76000,
      1
    ],

Some frames just went missing. 

I would like to ask @acpaquette, if possible, to see if file NLB_450492465EDR_F0310634NCAM00357M1.json is produced as it used to be from the LBL file. This is part of the MSL dataset that was shared around, so a prior copy of this exists. 

The LBL file is here: https://pds-imaging.jpl.nasa.gov/data/msl/MSLNAV_0XXX/DATA/SOL00597/NLB_450492465EDR_F0310634NCAM00357M1.LBL

Anybody encountered anything like that?

**Comment by oleg-alexandrov** [comment]
It is not something you did though. I can't reproduce what I did myself.

I will debug this. My request would be only for you to try to create an
ISD, without overwriting the old one, and seeing if there are frames
missing. (To ensure I am not hallucinating. :)

**Comment by acpaquette** [comment]
@oleg-alexandrov It looks like the ISD I sent and the new one I made from main both have the expected frame chains from ther ISD:
```
  "instrument_pointing": {
    "time_dependent_frames": [
      -76000,
      -76910,
      -76900,
      10014,
      1
    ],
```

What you produced is usually what happens if you just compute from source to destination using spice rather than the ALE FrameChain class but I am not sure why you are getting that.

**Comment by acpaquette** [comment]
What did you do to write the ISD? More importantly are the quaternions the same or are they different?

**Comment by oleg-alexandrov** [comment]
The quaternions changed too. 

All I did to create that ISD is the following:

```
import os, sys, json, ale

labelFile = sys.argv[1]
prefix = os.path.splitext(labelFile)[0]
usgscsm_str = ale.loads(labelFile, formatter = "ale",
                        verbose = True)

csm_isd = prefix + '.json'
print("Saving: " + csm_isd)
with open(csm_isd, 'w') as isd_file:
  isd_file.write(usgscsm_str)

```

Good to know the problem is on my side.

**Comment by acpaquette** [comment]
Huh, weird. You should need some form of kernels in the loads call unless they are already loaded. What kernels are you loading?

**Comment by oleg-alexandrov** [comment]
Good point. Aren't kernels loaded explicitly only from .cub files? This uses the spice data, so I assumed there's no need for kernels.

Should this invocation be modified somehow?

**Comment by oleg-alexandrov** [comment]
I looked very carefully at what you do and what I do, and found the source of the problem. I had "props={'nadir': True}" in the actual script I was using, but was instead trying to debug based on the documented script. 

Sorry. One of those crazy things that happen to everybody in a while. 

Thanks a lot. I could have figured it out without your help.

**Comment by acpaquette** [comment]
Sweet! Glad that was solved. Good to close?

**Comment by oleg-alexandrov** [comment]
Yay. I will close myself.
